version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/server/src
    ports:
      - 4000:4000
    env_file:
      - ./.env.dev
    # command: "npm run prod"
    links:
      - postgres

  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432
networks:
  default:
    external:
      name: auth-module
