version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/server/src
    ports:
      - 4000:4000
    env_file:
      - ./.dev.env
    # command: "npm run prod"
    links:
      - postgres

  postgres:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=studywebdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpasswd
    ports:
      - 5432:5432
networks:
  default:
    external:
      name: study-net
